name: C/C++ CI

# Controls when the action will run. Triggers the workflow on push
on:
  push:
  pull_request:
  release:
  # tags:
  # - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: ${{ config.name }}
    runs-on: ${{ config.os }} # будет запускаться по очереди на всех типах машин
    strategy:
      fail-fast: false
      config:
        - {
          name: "Ubuntu_Latest_GCC_Debug",
          os: ubuntu-latest,
          build_type: "Debug",
          cc: "gcc",
          cxx: "g++",
        }
        - {
          name: "Ubuntu_Latest_GCC_Release",
          os: ubuntu-latest,
          build_type: "Release",
          cc: "gcc",
          cxx: "g++",
        }

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}

      - name: Install dependencies on ubuntu
        if: startsWith(matrix.config.name, 'Ubuntu_Latest_GCC')
        run: |
          sudo apt-get update
          sudo apt-get install cmake
          ninja --version
          cmake --version
          gcc --version

      - name: Configure
        shell: bash
        run: |
          mkdir build
          mkdir instdir
          cmake \
            -S . \
            -B . \
            -DCMAKE_BUILD_TYPE=${{ config.build_type }} \
            -DCMAKE_INSTALL_PREFIX:PATH=instdir
      - name: Build
        shell: bash
        run: cmake --build . --config ${{ config.build_type }}